repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-docstring-first
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.1
  hooks:
  - id: pyupgrade
    args: [--py38-plus]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: ["--config=pyproject.toml"]
    files: "(ramsey|tests)"

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ["--settings-path=pyproject.toml"]
    files: "(ramsey|tests)"

- repo: https://github.com/pycqa/bandit
  rev: 1.7.0
  hooks:
  - id: bandit
    language: python
    language_version: python3
    types: [python]
    files: "(ramsey|tests)"
    args:
    - -s
    - B310 # ignore https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html?highlight=B310#b310-urllib-urlopen

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: python
    files: "ramsey"

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
    args: ["--ignore-missing-imports"]
    files: "(ramsey|tests)"
