[build-system]
requires = ["setuptools", "wheel"]

[tool.bandit]
skips = ["B101", "B310"]

[tool.ruff]
line-length = 80
exclude = ["*_test.py", "setup.py"]

[tool.ruff.lint]
ignore= ["S101", "ANN1", "ANN2", "ANN0"]
select = ["ANN", "D", "E", "F"]
extend-select = [
  "UP", "D", "I", "PL", "S"
]

[tool.ruff.lint.pydocstyle]
convention= 'numpy'
