name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

  test:
    name: unit tests
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install tox
    - name: Run format, sort, lints and types
      run: |
        tox -e  format,sort,lints,types
    - name: Run tests
      run: |
        tox -e tests

  coverage:
    name: code coverage
    runs-on: ubuntu-latest
    needs:
      - test
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install tox codecov
    - name: Compute code coverage
      run: |
        tox -e coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        env_vars: OS,PYTHON
        fail_ci_if_error: false
        verbose: true
        files: coverage.xml

  notebooks:
      name: notebooks and examples
      runs-on: ubuntu-latest
      needs:
        - test
      strategy:
        matrix:
          python-version: [3.9]
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install tox codecov
      - name: Run notebooks
        run: |
          tox -e notebooks
      - name: Run examples
        run: |
          tox -e examples
